version: '2'

services:
  shadowsocks:
    image: mritd/shadowsocks
    restart: always
    container_name: shadowsocks
    command:
     '-m "ss-server" -s "--fast-open -s 0.0.0.0 -p 443 -m chacha20-ietf-poly1305 -k <password> --plugin v2ray-plugin --plugin-opts=server;path=/shadowsocks;host=<domain.name>"'

  warp:
    build: ./warp
    restart: always
    cap_add:
     - MKNOD
     - AUDIT_WRITE
     - NET_ADMIN

  shadowsocks-warp:
    image: mritd/shadowsocks
    restart: always
    command:
      '-m "ss-server" -s "--fast-open -i CloudflareWARP -s 0.0.0.0 -p 443 -m chacha20-ietf-poly1305 -k <password> --plugin v2ray-plugin --plugin-opts=server;path=/shadowsocks/warp;host=<domain.name>"'
    container_name: shadowsocks-warp
    network_mode: service:warp

  caddy:
    image: xuzhenglun/caddy:cloudflare
    restart: always
    volumes:
     - ./caddy/Caddyfile:/etc/caddy/Caddyfile
     - ./caddy/data:/data
    ports:
     - 443:443
